# Generated by Django 4.2.4 on 2023-08-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'City',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='matchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofstadium', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.IntegerField(blank=True)),
                ('passport', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TICKET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('is_sold', models.BooleanField(default='False')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='model.city')),
                ('matchname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='model.matchlist')),
                ('stad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stad', to='model.stadium')),
            ],
        ),
    ]
