# Generated by Django 4.2.4 on 2023-08-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='matchname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='stad',
            field=models.CharField(max_length=255),
        ),
    ]
