# Generated by Django 4.2.4 on 2023-08-14 13:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_alter_matchlist_options_rename_name_matchlist_match_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='city',
            managers=[
                ('city_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
