# Generated by Django 4.2.4 on 2023-08-14 16:46

import contextlib
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_alter_city_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Ticket_class',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='Ticketclass',
            field=models.ForeignKey(default=contextlib.nullcontext, on_delete=django.db.models.deletion.CASCADE, related_name='tc', to='model.ticket_class'),
        ),
    ]
