# Generated by Django 4.2.4 on 2023-08-14 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_ticket_class_ticket_ticketclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Ticketclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tc', to='model.ticket_class'),
        ),
    ]
