# Generated by Django 4.2.4 on 2023-08-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_alter_ticket_ticketclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Ticketclass',
        ),
        migrations.DeleteModel(
            name='Ticket_class',
        ),
    ]
